### ISSUE TITLE
DEFECT: Unauthorized Access to Appointment Details

### ISSUE THREAD

**Issue by GiovaniFonseca** [GiovaniFonseca/iHealthy#42]
**Describe the bug**
There is a bug in the iHealthy website where user are able to view appointment details of other users by directly accessing the URL. This poses a security risk and violates privacy constraints. 

**To Reproduce**
1. Log in the iHealthy website as a user.
2. Go to the appointment list.
3. Paste the appointment URL that not belongs to you, in the search bar. 
4. Observe that the appointment details are displayed, despite not being the owner of the appointment.

**Expected behavior**
The expected behavior is that when a user tries to access an appointment that does not belong to them, they should be shown an error message indicating that they are not authorized to view the appointment details. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.5
 - Browser: Safari
 - Version: 14.1

**Additional context**
N/A

**Comment by Giov3ss** [comment]
**Resolution Steps:**

To address this issue, the following resolution steps were implemented:
1. In the **'detail'** view function of the appointment app, add the **'@login_required'** decorator before the function definition to ensure that only authenticated user can access the appointment details. 
2. Inside the **'detail'** view function, retrieve the appointment and then compare the **'appointment.user.id'** with the **'request.user.id'** to verify if the appointment belongs to the logged-in user.
3. If the appointment does not belong to the logged-in user, a message warning is displayed using the **'message.warning( )'** function to indicate that the user can only view their own appointments.
4. Additionally, will render the **'403.html'** template to provide a customized page notifying the user about the unauthorized access attempt.
